{
 "title": "common",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "country", "label": "Country", "query": "label_values(up, country)" },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(up{country=~\"$country\"}, env)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(up{country=~\"$country\"}, app)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(up{country=~\"$country\", env=~\"$env\", app=~\"$app\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{app=\"default\", country=~\"$country\"} == 1)"
    }
   ]
  },
  {
   "title": "DOWN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{app=\"default\", country=~\"$country\"} != 1)"
    }
   ]
  },
  {
   "title": "Docker_UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count(up{app=\"docker\", country=~\"$country\"} == 1)"
    }
   ]
  },
  {
   "title": "Docker_DOWN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{app=\"docker\", country=~\"$country\"} != 1)"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg by (name, job, country)(irate(node_cpu_seconds_total{mode=\"idle\", app=\"default\", country=~\"$country\", name=~\"$name\"}[30s]))",
     "legendFormat": "{{country}}-{{name}}"
    },
    {
     "expr": "1 - avg by (name, job, country)(irate(node_cpu{mode=\"idle\", app=\"default\", country=~\"$country\", name=~\"$name\"}[30s]))",
     "legendFormat": "{{country}}-{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{app=\"default\", country=~\"$country\", name=~\"$name\"} / node_memory_MemTotal_bytes{app=\"default\"} ",
     "legendFormat": "{{country}}-{{name}}"
    },
    {
     "expr": "1 - node_memory_MemAvailable{app=\"default\", country=~\"$country\", name=~\"$name\"} / node_memory_MemTotal{app=\"default\"} ",
     "legendFormat": "{{country}}-{{name}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{app=\"default\", device=~\"/dev/nvme0n1p1|/dev/root\", country=~\"$country\", name=~\"$name\"} / node_filesystem_size_bytes",
     "legendFormat": "{{country}}-{{name}} \"{{mountpoint}} : {{device}}\""
    },
    {
     "expr": "1 - node_filesystem_avail_bytes{app=\"default\", country=~\"$country\", env=\"prod\", name=~\"$name\", fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes",
     "legendFormat": "{{country}}-{{name}} \"{{mountpoint}} : {{device}}\""
    },
    {
     "expr": "1 - node_filesystem_free{app=\"default\", country=~\"$country\", env=\"uat\", name=~\"$name\", fstype=~\"ext4|xfs\"} / node_filesystem_size",
     "legendFormat": "{{country}}-{{name}} \"{{mountpoint}} : {{device}}\""
    }
   ]
  },
  {
   "title": "⇡ transmit / ⇣ receive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{app=\"default\", country=~\"$country\", name=~\"$name\"}  [5m])",
     "legendFormat": "{{country}}-{{name}}"
    },
    {
     "expr": "-irate(node_network_receive_bytes_total{app=\"default\", country=~\"$country\", name=~\"$name\"}  [5m])",
     "legendFormat": "{{country}}-{{name}}"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(engine_daemon_container_states_containers{app=\"docker\", state=\"running\", country=~\"$country\"} /\nignoring(state) sum without(state)(engine_daemon_container_states_containers{app=\"docker\"}))",
     "legendFormat": "{{country}}-{{name}}"
    }
   ]
  }
 ]
}