{
 "title": "nginx",
 "description": "Grafana Dashboard for Nginx Web Server.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(name, mode) (irate(node_cpu_seconds_total{name=\"nginx\"} [5m])) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_memory_MemFree_bytes/node_memory_MemTotal_bytes{name=\"nginx\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted [5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "irate(nginx_connections_handled [5m])",
     "legendFormat": "handled"
    },
    { "expr": "nginx_connections_active", "legendFormat": "active" },
    { "expr": "nginx_connections_reading", "legendFormat": "reading" },
    { "expr": "nginx_connections_waiting", "legendFormat": "waiting" },
    { "expr": "nginx_connections_writing", "legendFormat": "writing" },
    {
     "expr": "irate(nginx_http_requests_total [5m])",
     "legendFormat": "requests_total"
    }
   ]
  },
  {
   "title": "Disk ⇡ Read / ⇣ Write ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{name=\"nginx\"} [5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "-irate(node_disk_writes_completed_total{name=\"nginx\"} [5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}