# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "config/rule/*.yml"
  - "config/rule/alert/*.yml"

scrape_configs:
  - job_name: 'main'
    file_sd_configs:
    - refresh_interval: 5m
      files:
      - "config/main.yml"

  - job_name: pushgateway
    scrape_interval: 10s
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 5m
      files:
      - "config/pushgateway.yml"

# Script auto generate GCP/AWS config.
scrape_config_files:
  - config/azure/*.yml
  - config/gcp/main.yml
  - config/blackbox.yml
  - config/whois.yml
