global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'slack.hook'
receivers:
- name: 'slack.hook'
  slack_configs: 
  # Whether or not to notify about resolved alerts.
  - send_resolved: true
    api_url: http://<TOKEN_URL>
    # The channel or user to send notifications to.
    channel: '#alerting'
    username: 'Grafana'
    text: "<!channel> {{ range.Alerts }}\nsummary: {{ .Annotations.summary }}\ndescription: {{ .Annotations.description }}\n{{ end }}"
