global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'slack.hook'
  routes:
    - receiver: "gcp"
      group_wait: 30s
      matchers:
      - cloud=aws
    - receiver: "aws"
      group_wait: 30s
      matchers:
      - cloud=gcp
receivers:
- name: 'gcp'
  slack_configs: 
  - send_resolved: true
    api_url: https://<TOKEN_URL>
    channel: '#gcp'
    username: 'Prometheus'
    text: "<!channel> {{ range.Alerts }}\nsummary: {{ .Annotations.summary }}\ndescription: {{ .Annotations.description }}\n{{ end }}"
- name: 'aws'
  slack_configs: 
  - send_resolved: true
    api_url: https://<TOKEN_URL>
    channel: '#aws'
    username: 'Prometheus'
    text: "<!channel> {{ range.Alerts }}\nsummary: {{ .Annotations.summary }}\ndescription: {{ .Annotations.description }}\n{{ end }}"
