groups:
  - name: DomainCheck
    rules:
    - alert: HttpResponseBodyError
      expr: probe_failed_due_to_regex == 1
      for: 10m
      labels:
        severity: domain
      annotations:
        summary: "HTTP({{ $labels.instance }}) response body error."
        description: "{{ $labels.instance }} of job {{ $labels.job }} body not match regex."
    - alert: CertExpiry
      expr: ((probe_ssl_last_chain_expiry_timestamp_seconds) - time()) / 86400 < 7
      for: 1h
      labels:
        severity: domain
      annotations:
        summary: "Domain's({{ $labels.instance }}) cert is about to expire."
        description: "{{ $labels.instance }} of job {{ $labels.job }} will expire in {{ printf \"%.0f\" $value }} days."
    - alert: HttpLatancyTooHigh
      expr: sum without (phase) (probe_http_duration_seconds) > 1
      for: 30m
      labels:
        severity: domain
      annotations:
        summary: "HTTP({{ $labels.instance }}) access latency is too high."
        description: "{{ $labels.instance }} of job {{ $labels.job }} access latency {{ printf \"%.2f\" $value }}s, higher than 1s."
    - alert: HttpResponseCodeError
      expr:  probe_http_status_code > 300 or probe_http_status_code < 200
      for: 10m
      labels:
        severity: domain
      annotations:
        summary: "HTTP({{ $labels.instance }}) response code error."
        description: "{{ $labels.instance }} of job {{ $labels.job }} response code not equal 2xx."
    - alert: HttpRedirectFail
      expr: probe_http_redirects{redirect="on"} == 0
      for: 10m
      labels:
        severity: domain
      annotations:
        summary: "HTTP({{ $labels.instance }}) redirect fail."
        description: "{{ $labels.instance }} of job {{ $labels.job }} page not redirect."
