- targets:
  - 'prometheus:9090'
  labels:
    instance: 'monitor.yukifans.com:9090'
    app: 'prometheus'

- targets:
  - '192.168.0.1:9100'
  labels:
    instance: 'monitor.yukifans.com:9100'
    app: 'exporter'

- targets:
  - '192.168.0.1:9400'
  labels:
    instance: 'monitor.yukifans.com:9400'
    app: 'docker-exporter'
