global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'slack'
  routes:
  - receiver: 'gcp'
    matchers:
      cloud: gcp
    routes:
    - group_interval: 1d
      repeat_interval: 1d
      match:
        alertname: CertExpiry
      active_time_intervals:
      - cert
  - receiver: 'aws'
    matchers:
      cloud: aws
receivers:
- name: 'slack'
  slack_configs: 
  - send_resolved: true
    api_url: https://<TOKEN_URL>
    channel: '#common'
    username: 'Prometheus'
    text: "<!channel> {{ range.Alerts }}\nsummary: {{ .Annotations.summary }}\ndescription: {{ .Annotations.description }}\n{{ end }}"
- name: 'gcp'
  slack_configs: 
  - send_resolved: true
    api_url: https://<TOKEN_URL>
    channel: '#gcp'
    username: 'Prometheus'
    text: "<!channel> {{ range.Alerts }}\nsummary: {{ .Annotations.summary }}\ndescription: {{ .Annotations.description }}\n{{ end }}"
- name: 'aws'
  slack_configs: 
  - send_resolved: true
    api_url: https://<TOKEN_URL>
    channel: '#aws'
    username: 'Prometheus'
    text: "<!channel> {{ range.Alerts }}\nsummary: {{ .Annotations.summary }}\ndescription: {{ .Annotations.description }}\n{{ end }}"

time_intervals:
- name: cert
  time_intervals:
  - times:
  # UTC time.
    - start_time: 02:00
      end_time: 02:10
