version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/cert:/etc/nginx/cert:rw
      - ./nginx/index.txt:/usr/share/nginx/html/index.txt:ro
      - /var/log/nginx:/var/log/nginx
    restart: always
    logging:
      options:
        max-size: 100m
    ports:
      - 80:80
      - 443:443
    networks:
      - monitor
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=7d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./server/prometheus.yml:/etc/prometheus/prometheus.yml:rw
      - ./server/config/:/etc/prometheus/config/:rw
      - /data/monitor/prometheus:/prometheus
    restart: always
    logging:
      options:
        max-size: 100m
    networks:
      - monitor
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    command: 
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --web.external-url=https://localhost:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:rw
      - /data/monitor/alertmanager:/alertmanager:rw
    restart: always
    logging:
      options:
        max-size: 100m
    networks:
      - monitor
  pushgateway: 
    container_name: pushgateway
    image: prom/pushgateway
    restart: always
    logging:
      options:
        max-size: 100m
    networks:
      - monitor
    ports:
      - "9091:9091"
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/grafana.db:/var/lib/grafana/grafana.db:rw
    restart: always
    networks:
      - monitor
    logging:
      options:
        max-size: 100m
  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:0.10.0
    command: 
        - "-nginx.scrape-uri=http://nginx/metrics"
    restart: always
    networks:
      - monitor
    logging:
      options:
        max-size: 100m
  blackbox_exporter:
    container_name: blackbox-exporter
    image: quay.io/prometheus/blackbox-exporter:latest
    command:
      - --config.file=/config/blackbox.yml
    volumes:
      - ./exporter/blackbox:/config
    networks:
      - monitor
    logging:
      options:
        max-size: 100m
  whois_exporter:
    container_name: whois-exporter
    image: caarlos0/domain_exporter
    networks:
      - monitor
    logging:
      options:
        max-size: 100m
networks:
  monitor:
    name: monitor
