version: '3'

services:

  nginx:
    image: nginx:prom
    volumes:
      - /var/log/nginx:/var/log/nginx
    restart: always
    logging:
      options:
        max-size: 1g
    ports:
      - 80:80
      - 443:443
      - 9090:9090
      - 9093:9093
    networks:
      - monitor

  prometheus:
    image: prom/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=1d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus/server/prometheus.yml:/etc/prometheus/prometheus.yml:rw
      - ./prometheus/server/config/:/etc/prometheus/config/:rw
      - /data/monitor/prometheus:/prometheus
    restart: always
    logging:
      options:
        max-size: 1g
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager
    command: 
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --web.external-url=https://localhost:9093
    volumes:
      - ./prometheus/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:rw
      - /data/monitor/alertmanager:/alertmanager:rw
    restart: always
    logging:
      options:
        max-size: 1g
    networks:
      - monitor

  pushgateway:
    image: prom/pushgateway
    restart: always
    logging:
      options:
        max-size: 1g
    networks:
      - monitor
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    # volumes:
    #   - ./grafana.db:/var/lib/grafana/grafana.db:rw
    restart: always
    networks:
      - monitor
    logging:
      options:
        max-size: 1g

networks:
  monitor:
    name: monitor
