apiVersion: batch/v1
kind: CronJob
metadata:
  name: snedgrid-metrics
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: snedgrid-metrics
            image: 48763/sendgrid-metrics
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: sendgrid-config
              mountPath: /app/config
              subPath: config
          volumes:
          - name: sendgrid-config
            configMap:
              name: sendgrid-config
          restartPolicy: Never
