apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitor

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - config=config
  name: sendgrid-config

resources:
- cornjob.yml
