{
 "title": "Blackbox Exporter (HTTP prober)",
 "description": "Blackbox exporter HTTP prober dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, type)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(up{job=\"$job\", type=~\"$type\"}, app)"
    }
   },
   {
    "name": "module",
    "label": "Module",
    "query": {
     "query": "label_values(up{job=\"$job\", type=~\"$type\", app=~\"$app\"}, module)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\", type=~\"$type\", app=~\"$app\", module=~\"$module\"}, instance)"
    }
   },
   {
    "name": "tapp",
    "label": "App",
    "query": {
     "query": "label_values(up{job=\"$job\", app=~\"$app\"}, app)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(up{job=\"$job\", app=~\"$tapp\", instance=~\"$instance\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\", type=~\"$type\",app=~\"$app\", instance=~\"$instance\" , module=~\"$module\"}"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\", type=~\"$type\" ,app=~\"$app\" , instance=~\"$instance\" , module=~\"$module\"}"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{job=\"$job\", type=~\"$type\" ,app=~\"$app\" , instance=~\"$instance\" , module=~\"$module\"}"
    },
    {
     "expr": "probe_http_ssl{job=\"$job\", type=~\"$type\" ,app=~\"$app\" , instance=~\"$instance\" , module=~\"$module\"}"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=\"$job\", type=~\"$type\" ,app=~\"$app\" , instance=~\"$instance\" , module=~\"$module\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\", type=~\"$type\" ,app=~\"$app\" , instance=~\"$instance\" , module=~\"$module\"}"
    }
   ]
  },
  {
   "title": "$tapp: $target",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Duration Total",
   "type": "graph",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=\"$job\", app=~\"$tapp\", instance=\"$target\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "graph",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=\"$job\", app=~\"$tapp\", instance=\"$target\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}