# my global config
global:
  scrape_interval:     1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "config/rule/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'


    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'main'

    file_sd_configs:
    - refresh_interval: 30s
      files:
      - "config/main.yml"

# Script auto generate GCP config.

  - job_name: odin-default
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 30s
      files:
      - "config/gcp/odin/default.yml"

  - job_name: odin-elasticsearch
    metrics_path: /_prometheus/metrics
    file_sd_configs:
    - refresh_interval: 30s
      files:
      - "config/gcp/odin/elasticsearch.yml"

  - job_name: odin-docker
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 30s
      files:
      - "config/gcp/odin/docker.yml"
