groups:
  - name: Server
    rules:
    - alert: InstanceDown
      expr: up{node_status=~"on|"} == 0
      for: 1m
      labels:
        severity: instance
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
    - alert: DiskFull
      expr: (1 - node_filesystem_avail_bytes{job=~"prod-graylog|main|boss", device="/dev/sda1"} / node_filesystem_size_bytes{device="/dev/sda1"}) * 100 > 90
      for: 1m
      labels:
        severity: disk
      annotations:
        summary: "Instance {{ $labels.instance }} disk full"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been disk full for more than 1 minutes."
    - alert: BossVPN
      expr: absent(node_network_up{job="boss",instance="ubuntu-vpn-client:9100",device="ppp0"}) == 1
      for: 30s
      labels:
        severity: network
      annotations:
        summary: "Interface {{ $labels.instance }} down"
        description: "Interface {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds." 
