scrape_configs:
  - job_name: odin-default
    scrape_interval: 10s
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 5m
      files:
      - "odin/default.yml"

  - job_name: odin-elasticsearch
    scrape_interval: 150s
    metrics_path: /_prometheus/metrics
    file_sd_configs:
    - refresh_interval: 5m
      files:
      - "odin/elasticsearch.yml"

  - job_name: odin-docker
    scrape_interval: 10s
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 5m
      files:
      - "odin/docker.yml"
